functions:
  circles:
    lang: golang-middleware
    handler: ./micros/circles
    image: qolzam/circles:v0.202
    fprocess: ""
    environment: {}
    secrets:
    - secrets
    environment_file:
    - config/app_config.yml
    - config/circle_config.yml
    - config/server_web_config.yml
    - config/gateway_config.yml
    labels:
      com.openfaas.scale.zero: "false"
      openfaas-cloud: "1"
      role: ts-system
      telar.dev.appID: my-social-network
      telar.dev.repo: ts-serverless
    annotations:
      linkerd.io/inject: disabled
  comments:
    lang: golang-middleware
    handler: ./micros/comments
    image: qolzam/comments:v0.202
    fprocess: ""
    environment: {}
    secrets:
    - secrets
    environment_file:
    - config/app_config.yml
    - config/comment_config.yml
    - config/server_web_config.yml
    - config/gateway_config.yml
    labels:
      com.openfaas.scale.zero: "false"
      openfaas-cloud: "1"
      role: ts-system
      telar.dev.appID: my-social-network
      telar.dev.repo: ts-serverless
    annotations:
      linkerd.io/inject: disabled
  media:
    lang: golang-middleware
    handler: ./micros/gallery
    image: qolzam/media:v0.202
    fprocess: ""
    environment: {}
    secrets:
    - secrets
    environment_file:
    - config/app_config.yml
    - config/media_config.yml
    - config/server_web_config.yml
    - config/gateway_config.yml
    labels:
      com.openfaas.scale.zero: "false"
      openfaas-cloud: "1"
      role: ts-system
      telar.dev.appID: my-social-network
      telar.dev.repo: ts-serverless
    annotations:
      linkerd.io/inject: disabled
  posts:
    lang: golang-middleware
    handler: ./micros/posts
    image: qolzam/posts:v0.202
    fprocess: ""
    environment: {}
    secrets:
    - secrets
    environment_file:
    - config/app_config.yml
    - config/post_config.yml
    - config/server_web_config.yml
    - config/gateway_config.yml
    labels:
      com.openfaas.scale.zero: "false"
      openfaas-cloud: "1"
      role: ts-system
      telar.dev.appID: my-social-network
      telar.dev.repo: ts-serverless
    annotations:
      linkerd.io/inject: disabled
  user-rels:
    lang: golang-middleware
    handler: ./micros/user-rels
    image: qolzam/user-rels:v0.202
    fprocess: ""
    environment: {}
    secrets:
    - secrets
    environment_file:
    - config/app_config.yml
    - config/user_rel_config.yml
    - config/server_web_config.yml
    - config/gateway_config.yml
    labels:
      com.openfaas.scale.zero: "false"
      openfaas-cloud: "1"
      role: ts-system
      telar.dev.appID: my-social-network
      telar.dev.repo: ts-serverless
    annotations:
      linkerd.io/inject: disabled
  votes:
    lang: golang-middleware
    handler: ./micros/votes
    image: qolzam/votes:v0.202
    fprocess: ""
    environment: {}
    secrets:
    - secrets
    environment_file:
    - config/app_config.yml
    - config/vote_config.yml
    - config/server_web_config.yml
    - config/gateway_config.yml
    labels:
      com.openfaas.scale.zero: "false"
      openfaas-cloud: "1"
      role: ts-system
      telar.dev.appID: my-social-network
      telar.dev.repo: ts-serverless
    annotations:
      linkerd.io/inject: disabled
  vang:
    lang: golang-middleware
    handler: ./micros/vang
    image: qolzam/vang:v0.202
    fprocess: ""
    environment: {}
    secrets:
    - secrets
    environment_file:
    - config/app_config.yml
    - config/vang_config.yml
    - config/server_web_config.yml
    - config/gateway_config.yml
    labels:
      com.openfaas.scale.zero: "false"
      openfaas-cloud: "1"
      role: ts-system
      telar.dev.appID: my-social-network
      telar.dev.repo: ts-serverless
    annotations:
      linkerd.io/inject: disabled
provider:
  name: openfaas
  gateway: http://192.168.1.18:31112
